# Generated by Django 4.1.6 on 2023-02-09 16:35

from django.db import migrations, models
import django.db.models.deletion
import paytm_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(unique=True)),
                ('validity', models.PositiveIntegerField()),
                ('validity_type', models.CharField(choices=[('Days', 'Days')], max_length=20)),
                ('data', models.FloatField(max_length=5)),
                ('data_type', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB'), ('MB/Day', 'MB/Day'), ('GB/Day', 'GB/Day')], max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('operator', models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, related_name='operator_based_plan', to='paytm_app.operator')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_plan_type', to='paytm_app.categoryplan')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, validators=[paytm_app.models.Recharge.validate_mobile_number])),
                ('recharge_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytm_app.areacircle', to_field='area_name')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytm_app.operator', to_field='operator_name')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_detail', to='paytm_app.plan', to_field='price')),
            ],
        ),
    ]
